### PR TITLE
docs(runtime-site-config): add missing event parameter

### PR DESCRIPTION
**Pull request by dargmuesli**
### Description

`updateSiteConfig` should require `event` as first parameter. I also made it a bit more clear what `e` is and separated the if block from the assignment for (subjectively) better readability.

### Linked Issues

n/a

### Additional context

n/a

### CODE REVIEW

**Comment by harlan-zw** [comment]
Legend, thank you!

**Comment by dargmuesli** [comment]
Also, shouldn't it be `defineEventHandler` instead of `defineRequestMiddleware` for a server middleware?

**Comment by harlan-zw** [comment]
> Also, shouldn't it be `defineEventHandler` instead of `defineRequestMiddleware` for a server middleware? I think the nuxt docs only talk about `defineEventHandler`, `defineRequestMiddleware` should work as well but is more `h3`y.

They are interchangeable, I prefer this as it makes the scope clearer but not too fussed about changing it as I can see it from your side.

**Comment by dargmuesli** [comment]
All good, I was just wondering for a second.

**Pull request merged**
